# AUTOGENERATED FILE. DO NOT MODIFY.

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_file")
load("@rules_python//python:whl.bzl", "whl_library")

def pip_install():
    _existing_rules = native.existing_rules()

    if "whl__funcsigs_1_0_2__py2_py3_any" not in _existing_rules:
        http_file(
            name = "whl__funcsigs_1_0_2__py2_py3_any",
            urls = ["https://files.pythonhosted.org/packages/69/cb/f5be453359271714c01b9bd06126eaf2e368f1fddfff30818754b5ac2328/funcsigs-1.0.2-py2.py3-none-any.whl#sha256=330cc27ccbf7f1e992e69fef78261dc7c6569012cf397db8d3de0234e6c937ca"],
            sha256 = "330cc27ccbf7f1e992e69fef78261dc7c6569012cf397db8d3de0234e6c937ca",
            downloaded_file_path = "funcsigs-1.0.2-py2.py3-none-any.whl",
        )

    if "pypi__funcsigs_1_0_2__py27_any" not in _existing_rules:
        whl_library(
            name = "pypi__funcsigs_1_0_2__py27_any",
            whl = "@whl__funcsigs_1_0_2__py2_py3_any//file:funcsigs-1.0.2-py2.py3-none-any.whl",
            requirements = "@rules_python//python:requirements.bzl",
            extras = [],
            python_interpreter = "python2.7",
        )

    if "whl__mock_2_0_0__py2_py3_any" not in _existing_rules:
        http_file(
            name = "whl__mock_2_0_0__py2_py3_any",
            urls = ["https://files.pythonhosted.org/packages/e6/35/f187bdf23be87092bd0f1200d43d23076cee4d0dec109f195173fd3ebc79/mock-2.0.0-py2.py3-none-any.whl#sha256=5ce3c71c5545b472da17b72268978914d0252980348636840bd34a00b5cc96c1"],
            sha256 = "5ce3c71c5545b472da17b72268978914d0252980348636840bd34a00b5cc96c1",
            downloaded_file_path = "mock-2.0.0-py2.py3-none-any.whl",
        )

    if "pypi__mock_2_0_0__py27_any" not in _existing_rules:
        whl_library(
            name = "pypi__mock_2_0_0__py27_any",
            whl = "@whl__mock_2_0_0__py2_py3_any//file:mock-2.0.0-py2.py3-none-any.whl",
            requirements = "@rules_python//python:requirements.bzl",
            extras = [],
            python_interpreter = "python2.7",
        )

    if "whl__pbr_5_4_3__py2_py3_any" not in _existing_rules:
        http_file(
            name = "whl__pbr_5_4_3__py2_py3_any",
            urls = ["https://files.pythonhosted.org/packages/46/a4/d5c83831a3452713e4b4f126149bc4fbda170f7cb16a86a00ce57ce0e9ad/pbr-5.4.3-py2.py3-none-any.whl#sha256=b32c8ccaac7b1a20c0ce00ce317642e6cf231cf038f9875e0280e28af5bf7ac9"],
            sha256 = "b32c8ccaac7b1a20c0ce00ce317642e6cf231cf038f9875e0280e28af5bf7ac9",
            downloaded_file_path = "pbr-5.4.3-py2.py3-none-any.whl",
        )

    if "pypi__pbr_5_4_3__py27_any" not in _existing_rules:
        whl_library(
            name = "pypi__pbr_5_4_3__py27_any",
            whl = "@whl__pbr_5_4_3__py2_py3_any//file:pbr-5.4.3-py2.py3-none-any.whl",
            requirements = "@rules_python//python:requirements.bzl",
            extras = [],
            python_interpreter = "python2.7",
        )

    if "whl__pip_9_0_3__py2_py3_any" not in _existing_rules:
        http_file(
            name = "whl__pip_9_0_3__py2_py3_any",
            urls = ["https://files.pythonhosted.org/packages/ac/95/a05b56bb975efa78d3557efa36acaf9cf5d2fd0ee0062060493687432e03/pip-9.0.3-py2.py3-none-any.whl#sha256=c3ede34530e0e0b2381e7363aded78e0c33291654937e7373032fda04e8803e5"],
            sha256 = "c3ede34530e0e0b2381e7363aded78e0c33291654937e7373032fda04e8803e5",
            downloaded_file_path = "pip-9.0.3-py2.py3-none-any.whl",
        )

    if "pypi__pip_9_0_3__py27_any" not in _existing_rules:
        whl_library(
            name = "pypi__pip_9_0_3__py27_any",
            whl = "@whl__pip_9_0_3__py2_py3_any//file:pip-9.0.3-py2.py3-none-any.whl",
            requirements = "@rules_python//python:requirements.bzl",
            extras = [],
            python_interpreter = "python2.7",
        )

    if "whl__setuptools_38_2_4__py2_py3_any" not in _existing_rules:
        http_file(
            name = "whl__setuptools_38_2_4__py2_py3_any",
            urls = ["https://files.pythonhosted.org/packages/bb/e0/ea620f9ecbaaaf3ebb288cdbbe8cc20b6a789c17e42d8916662b218e3349/setuptools-38.2.4-py2.py3-none-any.whl#sha256=ca69216173b631cc29314bbce4d0b7e8a69784c8b6d7ea6b9e4952ac9ec0897d"],
            sha256 = "ca69216173b631cc29314bbce4d0b7e8a69784c8b6d7ea6b9e4952ac9ec0897d",
            downloaded_file_path = "setuptools-38.2.4-py2.py3-none-any.whl",
        )

    if "pypi__setuptools_38_2_4__py27_any" not in _existing_rules:
        whl_library(
            name = "pypi__setuptools_38_2_4__py27_any",
            whl = "@whl__setuptools_38_2_4__py2_py3_any//file:setuptools-38.2.4-py2.py3-none-any.whl",
            requirements = "@rules_python//python:requirements.bzl",
            extras = ["ssl"],
            python_interpreter = "python2.7",
        )

    if "whl__six_1_13_0__py2_py3_any" not in _existing_rules:
        http_file(
            name = "whl__six_1_13_0__py2_py3_any",
            urls = ["https://files.pythonhosted.org/packages/65/26/32b8464df2a97e6dd1b656ed26b2c194606c16fe163c695a992b36c11cdf/six-1.13.0-py2.py3-none-any.whl#sha256=1f1b7d42e254082a9db6279deae68afb421ceba6158efa6131de7b3003ee93fd"],
            sha256 = "1f1b7d42e254082a9db6279deae68afb421ceba6158efa6131de7b3003ee93fd",
            downloaded_file_path = "six-1.13.0-py2.py3-none-any.whl",
        )

    if "pypi__six_1_13_0__py27_any" not in _existing_rules:
        whl_library(
            name = "pypi__six_1_13_0__py27_any",
            whl = "@whl__six_1_13_0__py2_py3_any//file:six-1.13.0-py2.py3-none-any.whl",
            requirements = "@rules_python//python:requirements.bzl",
            extras = [],
            python_interpreter = "python2.7",
        )

    if "whl__wheel_0_30_0a0__py2_py3_any" not in _existing_rules:
        http_file(
            name = "whl__wheel_0_30_0a0__py2_py3_any",
            urls = ["https://files.pythonhosted.org/packages/83/53/e120833aa2350db333df89a40dea3b310dd9dabf6f29eaa18934a597dc79/wheel-0.30.0a0-py2.py3-none-any.whl#sha256=cd19aa9325d3af1c641b0a23502b12696159171d2a2f4b84308df9a075c2a4a0"],
            sha256 = "cd19aa9325d3af1c641b0a23502b12696159171d2a2f4b84308df9a075c2a4a0",
            downloaded_file_path = "wheel-0.30.0a0-py2.py3-none-any.whl",
        )

    if "pypi__wheel_0_30_0a0__py27_any" not in _existing_rules:
        whl_library(
            name = "pypi__wheel_0_30_0a0__py27_any",
            whl = "@whl__wheel_0_30_0a0__py2_py3_any//file:wheel-0.30.0a0-py2.py3-none-any.whl",
            requirements = "@rules_python//python:requirements.bzl",
            extras = ["tool"],
            python_interpreter = "python2.7",
        )

_requirements = {
    "funcsigs": ["@pypi__funcsigs_1_0_2__py27_any//:pkg"],
    "mock": ["@pypi__mock_2_0_0__py27_any//:pkg"],
    "pbr": ["@pypi__pbr_5_4_3__py27_any//:pkg"],
    "pip": ["@pypi__pip_9_0_3__py27_any//:pkg"],
    "setuptools": ["@pypi__setuptools_38_2_4__py27_any//:pkg"],
    "setuptools[ssl]": ["@pypi__setuptools_38_2_4__py27_any//:ssl"],
    "six": ["@pypi__six_1_13_0__py27_any//:pkg"],
    "wheel": ["@pypi__wheel_0_30_0a0__py27_any//:pkg"],
    "wheel[tool]": ["@pypi__wheel_0_30_0a0__py27_any//:tool"],
}

def requirement(name):
    fail("requirement() has been renamed requirements(). It now takes and returns a list instead of a string.")

def requirements(names):
    if type(names) != "list":
        fail("requirements() now takes a list and returns a list")

    deps = []
    for name in names:
        name_key = name.replace("-", "_").lower()
        if name_key not in _requirements:
            fail("Could not find pip-provided dependency: '%s'" % name)
        deps += _requirements[name_key]
    return deps
